import React, { useRef, useState } from 'react'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import { Download, FileText, Search } from 'lucide-react'
import useAxiosSecure from '../hooks/useAxiosSecure'
import { useQuery } from '@tanstack/react-query'
import Pdf from '../components/Pdf'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'





const TaxVatRate = () => {
  const [search, setSearch] = useState('')
  const axiosSecure=useAxiosSecure();
  const pdfRef = useRef();
  const {data:taxVatData=[]}=useQuery(
    {
      queryKey:['taxVatRates'],
      queryFn:async()=>
      {
        const res=await axiosSecure.get('/taxvatrates');
        return res.data;
      }

    }
  )


  const filtered = taxVatData.filter(item =>
    item.name.toLowerCase().includes(search.toLowerCase()) ||
    item.category.toLowerCase().includes(search.toLowerCase())
  )
  
  const handleDownloadPDF = () => {
    try {
      if (filtered.length === 0) {
        alert('No data to generate PDF. Please perform a search first.');
        return;
      }

      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      let yPosition = 20;

      // Add title
      doc.setFontSize(18);
      doc.setTextColor(99, 102, 241); // Primary color
      doc.text('Tax & VAT Rates', pageWidth / 2, yPosition, { align: 'center' });
      
      yPosition += 8;
      doc.setFontSize(11);
      doc.setTextColor(107, 114, 128);
      doc.text('Official tax and VAT rates based on National Board of Revenue guidelines', pageWidth / 2, yPosition, { align: 'center' });

      // Add generated date
      yPosition += 12;
      const currentDate = new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      });
      doc.setFontSize(10);
      doc.setTextColor(107, 114, 128);
      doc.text(`Generated: ${currentDate}`, 20, yPosition);
      doc.text(`Total Records: ${filtered.length}`, pageWidth - 20, yPosition, { align: 'right' });

      // Prepare table data
      const tableData = filtered.map((item, index) => [
        item.id,
        item.name,
        item.category,
        `${item.vatRate}%`,
        `${item.incomeTaxRate}%`,
        
      ]);

      // Add table
      yPosition += 10;
      autoTable(doc, {
        head: [['Serial No', 'Product/Service Name', 'Type', 'VAT (%)', 'Tax (%)']],
        body: tableData,
        startY: yPosition,
        theme: 'grid',
        headStyles: {
          fillColor: [87, 13, 248],
          textColor: [255, 255, 255],
          fontStyle: 'bold',
          fontSize: 10,
          halign: 'center',
          lineColor: [219, 221, 225],
          lineWidth: 0.3
          
        },
        bodyStyles: {
          textColor: [55, 65, 81],
          fontSize: 9,
          lineColor: [219, 221, 225],
          lineWidth: 0.3
        },
        alternateRowStyles: {
          fillColor: [249, 250, 251]
        },
        columnStyles: {
          0: { halign: 'center', cellWidth: 24 },
          1: { halign: 'left', cellWidth: 80 },
          2: { halign: 'center', cellWidth: 24 },
          3: { halign: 'center', cellWidth: 20 },
          4: { halign: 'center', cellWidth: 20 },
          
        },
        margins: { left: 15, right: 15 },
        didDrawPage: (data) => {
          // Footer
          const footerY = doc.internal.pageSize.getHeight() - 5;
          doc.setFontSize(9);
          doc.setTextColor(156, 163, 175);
          doc.text('This document was automatically generated by NSTU TaxDesk System', pageWidth / 2, footerY, { align: 'center' });
        }
      });

      // Add footer information on last page
      const finalY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 15 : yPosition + 60;
      doc.setFontSize(10);
      doc.setTextColor(31, 41, 55);
      doc.text('Important Information', 20, finalY);
      
      doc.setFontSize(9);
      doc.setTextColor(75, 85, 99);
      doc.text('• All rates are subject to change based on NBR guidelines', 25, finalY + 7);
      doc.text('• VAT and Tax are calculated on the gross amount of the service', 25, finalY + 14);
      doc.text('• For detailed calculation, please use the Tax Calculator', 25, finalY + 21);
      doc.text('• Contact the Finance Department for any clarifications', 25, finalY + 28);

      // Save the PDF
      doc.save('tax-vat-rates.pdf');
    } catch (error) {
      console.error('PDF Error:', error);
      alert('Failed to generate PDF: ' + error.message);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <Navbar />

      <section className="!px-4 sm:!px-5 lg:!px-7 !py-6 lg:!py-8">
        <div className="w-full max-w-7xl !mx-auto">
          <div className='flex items-start sm:items-center justify-start gap-3 sm:gap-4'>
            <div className="text-primary rounded-2xl w-14 h-14 sm:w-16 sm:h-16 flex shrink-0 items-center justify-center !p-3 bg-[#E9E7F7]">
              <FileText size={30} />
            </div>
            <div>
              <h1 className='text-2xl sm:text-3xl font-bold text-gray-900'>Tax & VAT Rates</h1>
              <p className='text-gray-700 text-sm sm:text-base !mt-1'>Official tax and VAT rates based on National Board of Revenue guidelines.</p>
            </div>
          </div>

          <div className='w-full bg-white shadow-sm border border-gray-200 flex flex-col sm:flex-row sm:items-center gap-3 rounded-2xl !px-4 sm:!px-5 !py-4 sm:!py-5 !mt-6'>
            <div className='relative flex-1'>
              <Search size={16} className='absolute left-3 top-1/2 -translate-y-1/2 text-gray-400' />
              <input
                type="text"
                placeholder="Search product or service..."
                value={search}
                onChange={e => setSearch(e.target.value)}
                className="w-full rounded-lg bg-gray-100 border border-gray-200 !pl-9 !pr-3 !py-2.5 text-sm focus:outline-none focus:border-primary"
              />
            </div>
            <button onClick={handleDownloadPDF} className="btn btn-primary flex items-center gap-2 !px-5 !py-2 rounded-lg text-sm whitespace-nowrap">
              <Download size={16} /> Download PDF
            </button>
          </div>
          <p className='text-sm text-gray-500 !mt-3'>
            Showing <span className='font-semibold text-gray-700'>{filtered.length}</span> of <span className='font-semibold text-gray-700'>{taxVatData.length}</span> services
          </p>

          <div className="overflow-x-auto w-full !my-6 rounded-xl shadow-sm border border-gray-200 bg-white">
            <table className="min-w-[900px] w-full text-sm text-left">
              <thead>
                <tr className="bg-primary text-white">
                  <th className="!px-6 !py-4 font-semibold text-base w-30">Serial No</th>
                  <th className="!px-6 !py-4 font-semibold text-base">Product/Service Name</th>
                  <th className="!px-6 !py-4 font-semibold text-base text-center">Type</th>
                  <th className="!px-6 !py-4 font-semibold text-base text-center">VAT (%)</th>
                  <th className="!px-6 !py-4 font-semibold text-base text-center">Tax (%)</th>
                  <th className="!px-6 !py-4 font-semibold text-base text-center">Total Rate (%)</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-100">
                {filtered.length > 0 ? filtered.map((item) => {
                  const isProduct = item.category?.toLowerCase() === 'product'

                  return (
                    <tr key={item.id} className="hover:bg-indigo-50/40 transition-colors">
                      <td className="!px-6 !py-5 text-gray-600 font-medium">{item.id}</td>
                      <td className="!px-6 !py-5 text-gray-800 font-medium">{item.name}</td>
                      <td className="!px-6 !py-5 text-center">
                        <span className={`!px-3 !py-1 rounded-full text-xs font-semibold ${isProduct ? 'bg-blue-100 text-blue-600' : 'bg-purple-100 text-purple-600'}`}>
                          {item.category}
                        </span>
                      </td>
                      <td className="!px-6 !py-5 text-center">
                        <span className="inline-block bg-blue-50 text-blue-500 font-semibold text-sm !px-4 !py-1.5 rounded-full min-w-[52px]">
                          {item.vatRate}%
                        </span>
                      </td>
                      <td className="!px-6 !py-5 text-center">
                        <span className="inline-block bg-green-50 text-green-600 font-semibold text-sm !px-4 !py-1.5 rounded-full min-w-[52px]">
                          {item.incomeTaxRate}%
                        </span>
                      </td>
                      <td className="!px-6 !py-5 text-center">
                        <span className="inline-block bg-purple-50 text-purple-500 font-semibold text-sm !px-4 !py-1.5 rounded-full min-w-[52px]">
                          {parseFloat(item.vatRate) + parseFloat(item.incomeTaxRate)}%
                        </span>
                      </td>
                    </tr>
                  )
                }) : (
                  <tr>
                    <td colSpan={6} className="!px-6 !py-10 text-center text-gray-400">
                      No results found for &quot;{search}&quot;
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          <div className="w-full !mb-4 rounded-xl border border-blue-100 bg-[#E9E7F7] !px-5 sm:!px-6 !py-5 sm:!py-6">
            <div className="flex items-center gap-3 !mb-4">
              <FileText size={22} className="text-black" />
              <h2 className="text-lg font-bold text-black">Important Information</h2>
            </div>
            <ul className="space-y-2 text-sm text-black">
              <li className="flex items-start gap-2"><span className="mt-0.5 text-black font-bold">•</span> All rates are subject to change based on NBR guidelines</li>
              <li className="flex items-start gap-2"><span className="mt-0.5 text-black font-bold">•</span> VAT and Tax are calculated on the gross amount of the service</li>
              <li className="flex items-start gap-2"><span className="mt-0.5 text-black font-bold">•</span> For detailed calculation, please use the Tax Calculator</li>
              <li className="flex items-start gap-2"><span className="mt-0.5 text-black font-bold">•</span> Contact the Finance Department for any clarifications</li>
            </ul>
          </div>
        </div>
      </section>

      <Footer />
      <div style={{ position: "absolute", left: "-9999px", top: 0 }}>
  <div ref={pdfRef}>
    <Pdf data={filtered} />
  </div>
</div>
    </div>
  )
}

export default TaxVatRate